parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 2018
  project: 'tsconfig.json'
  tsconfigRootDir: '.'

extends:
  - plugin:@typescript-eslint/recommended
  - plugin:node/recommended-module
  - plugin:prettier/recommended
  - prettier/@typescript-eslint

plugins:
  - "@typescript-eslint"
  - prettier

rules:
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-unused-vars": 
    - error
    - ignoreRestSiblings: true
  node/no-missing-import:
    - error
    - tryExtensions:
        - .ts
        - .js
        - .json
  node/shebang: off

overrides:
  - files:
      - 'rollup.config.ts'
    rules:
      "node/no-unpublished-require": off
