name: Main

on:
  pull_request:
    branches:
    - "*"
  push:
    branches:
    - "*"
    tags-ignore:
    - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Typecheck
        run: npm run typecheck
      - name: Build 
        run: |
          npm run build
          npm pack
          mv *.tgz package.tgz
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: package.tgz
